language: python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
script:
  - hass -c . --script check_config
matrix:
  include:
    - before_install: pip3 install homeassistant
    - before_install: pip3 install https://github.com/home-assistant/home-assistant/archive/dev.zip#homeassistant
