language: python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
env:
  - PIP_SOURCE=homeassistant
  - PIP_SOURCE=https://github.com/home-assistant/home-assistant/archive/dev.zip#homeassistant
install:
  - pip3 install $PIP_SOURCE
script:
  - hass -c . --script check_config
