homeassistant:
  name: TwelveTwelve
  unit_system: imperial
  time_zone: America/Los_Angeles
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 8
  customize: !include_dir_merge_named customize
  customize_glob:
    "media_player.plex_*":
      haaska_hidden: true

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  use_x_forwarded_for: yes

config:

mqtt:
  broker: 192.168.1.3
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password

zwave:
  usb_path: /dev/zwave
  config_path: /home/robbiet480/home-assistant/venv/lib/python3.5/site-packages/python_openzwave/ozw_config
  network_key: !secret zwave_network_key
  new_entity_ids: true
  device_config:
    light.entrance_hallway_overhead_lights_accessory_level:
      ignored: true
    light.interior_hallway_overhead_lights_accessory_level:
      ignored: true
    sensor.brandons_bedroom_multisensor_alarm_level:
      ignored: true
    sensor.brandons_bedroom_multisensor_alarm_type:
      ignored: true
    sensor.brandons_bedroom_multisensor_burglar:
      ignored: true
    sensor.brandons_bedroom_multisensor_sourcenodeid:
      ignored: true
    sensor.living_room_multisensor_alarm_level:
      ignored: true
    sensor.living_room_multisensor_alarm_type:
      ignored: true
    sensor.living_room_multisensor_burglar:
      ignored: true
    sensor.living_room_multisensor_sourcenodeid:
      ignored: true
    sensor.robbies_bedroom_bed_occupancy_sensor_alarm_level:
      ignored: true
    sensor.robbies_bedroom_bed_occupancy_sensor_alarm_type:
      ignored: true
    sensor.robbies_bedroom_bed_occupancy_sensor_burglar:
      ignored: true
    sensor.robbies_bedroom_bed_occupancy_sensor_sourcenodeid:
      ignored: true
    sensor.robbies_bedroom_door_alarm_level:
      ignored: true
    sensor.robbies_bedroom_door_alarm_type:
      ignored: true
    sensor.robbies_bedroom_door_burglar:
      ignored: true
    sensor.robbies_bedroom_door_sourcenodeid:
      ignored: true
    sensor.robbies_bedroom_multisensor_alarm_level:
      ignored: true
    sensor.robbies_bedroom_multisensor_alarm_type:
      ignored: true
    sensor.robbies_bedroom_multisensor_burglar:
      ignored: true
    sensor.robbies_bedroom_multisensor_sourcenodeid:
      ignored: true
    switch.entrance_hallway_overhead_lights_accessory_switch:
      ignored: true
    switch.interior_hallway_overhead_lights_accessory_switch:
      ignored: true

zha:
  usb_path: /dev/zigbee
  database_path: /home/robbiet480/.homeassistant/zigbee.db

discovery:

logger:
  default: info
frontend:
  themes:
    happy:
      primary-color: pink
    sad:
      primary-color: blue
    red:
      primary-color: "#f44336"
    pink:
      primary-color: "#e91e63"
    purple:
      primary-color: "#9c27b0"
    deep-purple:
      primary-color: "#673ab7"
    indigo:
      primary-color: "#3f51b5"
    blue:
      primary-color: "#2196f3"
    light-blue:
      primary-color: "#03a9f4"
    cyan:
      primary-color: "#00bcd4"
    teal:
      primary-color: "#009688"
    green:
      primary-color: "#4caf50"
    light-green:
      primary-color: "#8bc34a"
    lime:
      primary-color: "#cddc39"
    yellow:
      primary-color: "#ffeb3b"
    amber:
      primary-color: "#ffc107"
    orange:
      primary-color: "#ff9800"
    deep-orange:
      primary-color: "#ff5722"
    brown:
      primary-color: "#795548"
    grey:
      primary-color: "#9e9e9e"
    blue-grey:
      primary-color: "#607d8b"
history:
sun:
logbook:
updater:
recorder:
  db_url: !secret recorder_db_url
  purge_interval: 2
  purge_keep_days: 14

#emulated_hue:
#  exposed_domains: ['switch', 'light', 'fan', 'media_player']
#  host_ip: 192.168.1.3
#  listen_port: 8300

#hdmi_cec:
#  host: 192.168.1.33
#  devices:
#    Toshiba TV: 0.0.0.0
#    Apple TV: 1.0.0.0
#    Roku: 2.0.0.0
#    PlayStation 4: 3.0.0.0

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: !secret aws_region

ios:

influxdb:
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: !secret influxdb_database

foursquare:
  access_token: !secret foursquare_access_token
  push_secret: !secret foursquare_push_token

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

tradfri:
  host: !secret tradfri_ip
  api_key: !secret tradfri_api_key
  allow_tradfri_groups: false

#alert: !include_dir_named alerts/
alexa:
  flash_briefings: !include_dir_named alexa/flash_briefings/
automation: !include automations.yaml
binary_sensor: !include_dir_merge_list devices/binary_sensors/
camera: !include_dir_merge_list devices/cameras/
device_tracker: !include_dir_merge_list devices/device_trackers/
fan: !include_dir_merge_list devices/fans/
group: !include_dir_named groups/
intent_script: !include_dir_named alexa/intents/
light: !include_dir_merge_list devices/lights/
media_player: !include_dir_merge_list devices/media_players/
notify: !include_dir_merge_list notifies/
script: !include_dir_named scripts/
sensor: !include_dir_merge_list devices/sensors/
switch: !include_dir_merge_list devices/switches/
zone: !include_dir_merge_list zones/

apple_tv:
  - name: Living Room Apple TV
    host: 192.168.1.35
    login_id: 00000000-0ba7-9abb-857f-3f12f3b94448
  - name: Robbie's Room Apple TV
    login_id: 00000000-0ba7-9abb-857f-3f12f3b94448
    host: 192.168.1.36

amcrest:
  - host: !secret amcrest_ip
    name: "New Construction"
    username: !secret amcrest_username
    password: !secret amcrest_password
    resolution: high
    stream_source: snapshot
    sensors:
      - motion_detector
      - ptz_preset
