homeassistant:
  name: TwelveTwelve
  unit_system: imperial
  time_zone: America/Los_Angeles
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 8
  customize: !include_dir_merge_named customize
  customize_glob:
    "media_player.plex_*":
      haaska_hidden: true

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  use_x_forwarded_for: yes

config:

mqtt:
  broker: 192.168.1.3
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password

zwave:
  usb_path: /dev/zwave
  config_path: /home/robbiet480/home-assistant/venv/lib/python3.5/site-packages/python_openzwave/ozw_config
  #network_key: !secret zwave_network_key
  device_config:
    light.entrance_hallway_overhead_lights_accessory_level_8_0:
      ignored: true
    light.interior_hallway_overhead_lights_accessory_level_11_0:
      ignored: true
    sensor.brandons_bedroom_multisensor_alarm_level_20_1:
      ignored: true
    sensor.brandons_bedroom_multisensor_alarm_type_20_0:
      ignored: true
    sensor.brandons_bedroom_multisensor_burglar_20_10:
      ignored: true
    sensor.brandons_bedroom_multisensor_sourcenodeid_20_2:
      ignored: true
    sensor.living_room_multisensor_alarm_level_9_1:
      ignored: true
    sensor.living_room_multisensor_alarm_type_9_0:
      ignored: true
    sensor.living_room_multisensor_burglar_9_10:
      ignored: true
    sensor.living_room_multisensor_sourcenodeid_9_2:
      ignored: true
    sensor.robbies_bedroom_bed_occupancy_sensor_alarm_level_17_1:
      ignored: true
    sensor.robbies_bedroom_bed_occupancy_sensor_alarm_type_17_0:
      ignored: true
    sensor.robbies_bedroom_bed_occupancy_sensor_burglar_17_10:
      ignored: true
    sensor.robbies_bedroom_bed_occupancy_sensor_sourcenodeid_17_2:
      ignored: true
    sensor.robbies_bedroom_door_alarm_level_14_1:
      ignored: true
    sensor.robbies_bedroom_door_alarm_type_14_0:
      ignored: true
    sensor.robbies_bedroom_door_burglar_14_10:
      ignored: true
    sensor.robbies_bedroom_door_sourcenodeid_14_2:
      ignored: true
    sensor.robbies_bedroom_multisensor_alarm_level_15_1:
      ignored: true
    sensor.robbies_bedroom_multisensor_alarm_type_15_0:
      ignored: true
    sensor.robbies_bedroom_multisensor_burglar_15_10:
      ignored: true
    sensor.robbies_bedroom_multisensor_sourcenodeid_15_2:
      ignored: true
    switch.entrance_hallway_overhead_lights_accessory_switch_8_0:
      ignored: true
    switch.interior_hallway_overhead_lights_accessory_switch_11_0:
      ignored: true

discovery:

logger:
  default: info
frontend:
history:
sun:
logbook:
updater:
recorder:
  db_url: !secret recorder_db_url
  purge_days: 14

#emulated_hue:
#  exposed_domains: ['switch', 'light', 'fan', 'media_player']
#  host_ip: 192.168.1.3
#  listen_port: 8300

#hdmi_cec:
#  host: 192.168.1.33
#  devices:
#    Toshiba TV: 0.0.0.0
#    Apple TV: 1.0.0.0
#    Roku: 2.0.0.0
#    PlayStation 4: 3.0.0.0

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: !secret aws_region

ios:

influxdb:
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: !secret influxdb_database

foursquare:
  access_token: !secret foursquare_access_token
  push_secret: !secret foursquare_push_token

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

tradfri:
  host: !secret tradfri_ip
  api_key: !secret tradfri_api_key

#alert: !include_dir_named alerts/
alexa:
  flash_briefings: !include_dir_named alexa/flash_briefings/
  intents: !include_dir_named alexa/intents/
automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list devices/binary_sensors/
camera: !include_dir_merge_list devices/cameras/
device_tracker: !include_dir_merge_list devices/device_trackers/
fan: !include_dir_merge_list devices/fans/
group: !include_dir_named groups/
light: !include_dir_merge_list devices/lights/
media_player: !include_dir_merge_list devices/media_players/
notify: !include_dir_merge_list notifies/
script: !include_dir_named scripts/
sensor: !include_dir_merge_list devices/sensors/
switch: !include_dir_merge_list devices/switches/
zone: !include_dir_merge_list zones/
