- platform: mqtt_json
  name: "Robbie's Room Window LED Strip"
  state_topic: 'RGBW/000CCF48/json/state'
  command_topic: 'RGBW/000CCF48/json/set'
  brightness: true
  color_temp: true
  rgb: true
  white_value: true

- platform: mqtt
  name: 'Living Room Window LED Strip'
  state_topic: 'RGBW/000CCA97/json/state'
  command_topic: 'RGBW/000CCA97/json/set'
  brightness: true
  color_temp: true
  rgb: true
  white_value: true
