- platform: mqtt
  name: "Robbie's Room RGB LED Strip"
  state_topic: 'RGBW/000CCF48/state/state'
  command_topic: 'RGBW/000CCF48/state/set'
  brightness_state_topic: 'RGBW/000CCF48/brightness/state'
  brightness_command_topic: 'RGBW/000CCF48/brightness/set'
  rgb_state_topic: 'RGBW/000CCF48/color/state'
  rgb_command_topic: 'RGBW/000CCF48/color/set'

- platform: mqtt
  name: 'New Arilux RGBW LED Controller'
  state_topic: 'RGBW/000CCA97/state/state'
  command_topic: 'RGBW/000CCA97/state/set'
  brightness_state_topic: 'RGBW/000CCA97/brightness/state'
  brightness_command_topic: 'RGBW/000CCA97/brightness/set'
  rgb_state_topic: 'RGBW/000CCA97/color/state'
  rgb_command_topic: 'RGBW/000CCA97/color/set'
