- platform: flux
  lights:
    - light.front_lamp
    - light.hallway_bloom
    - light.rear_lamp
    - light.robbies_bedside__left
    - light.robbies_bedside__right
    - light.robbies_floorstanding
    - light.robbies_strip
    - light.under_counter
