- alias: Front door is open
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor_10_0
    from: 'off'
    to: 'on'
  action:
    service: notify.humansanddisplays
    data:
      title: Front door
      message: The front door is open
      data:
        push:
          sound: US-EN-Daisy-Front-Door-Open.wav

- alias: Turn on entrance hallway overhead when the door opens
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor_10_0
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_entrance_hallway_overhead
