- alias: Notify if Robbie's door is opened when he isn't home
  trigger:
    platform: state
    entity_id: binary_sensor.robbies_bedroom_door_sensor_12_0
    from: "off"
    to: "on"
  condition:
    condition: state
    entity_id: device_tracker.robbies_iphone_7_plus
    state: "not_home"
  action:
    service: notify.robbiesdevices
    data_template:
      message: >
        Bedroom door is {% if trigger.to_state.state == "on" %}open{% else %}closed{% endif %} (you aren't at home!)

- alias: Notify if there is motion in Robbie's Room when he isn't home
  trigger:
    platform: state
    entity_id: binary_sensor.robbies_room_multisensor_6_sensor_21_0
    from: "off"
    to: "on"
  condition:
    condition: state
    entity_id: device_tracker.robbies_iphone_7_plus
    state: "not_home"
  action:
    service: notify.robbiesdevices
    data:
      message: "Motion in your bedroom (you aren't at home!)"
      data:
        push:
          sound: "US-EN-Morgan-Freeman-Motion-In-Bedroom.wav"
