- alias: Robbie arrived home
  trigger:
    platform: state
    entity_id: device_tracker.robbies_iphone_7_plus
    from: 'not_home'
    to: 'home'
  action:
    service: light.turn_on
    entity_id: group.robbies_room
    data:
      brightness: 255
      rgb_color: [255, 255, 255]

- alias: Robbie left home
  trigger:
    platform: state
    entity_id: device_tracker.robbies_iphone_7_plus
    from: 'home'
    to: 'not_home'
  action:
    service: homeassistant.turn_off
    entity_id:
      - group.robbiesroom
