- alias: Send a notification 1 hour before sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    service: notify.robbiesdevices
    data:
      message: 'There is one hour remaining until sunset.'

- alias: End of day sunset notification
  trigger:
    platform: sun
    event: sunset
  action:
    service: notify.robbiesdevices
    data_template:
      message: >
        Sunset for {{ now().strftime('%A %B %-d, %Y at %-I:%M %p') }}!
        The day's high temperature in Oakland was {{ states.sensor.dark_sky_daily_high_temperature.state }}{{ states.sensor.dark_sky_daily_high_temperature.attributes.unit_of_measurement }}.
        The low temperature today was {{ states.sensor.dark_sky_daily_low_temperature.state }}{{ states.sensor.dark_sky_daily_low_temperature.attributes.unit_of_measurement }}.
        The current conditions are {{ states.sensor.dark_sky_minutely_summary.state|lower }}.
        {% for name, zone in states.device_tracker|groupby('state') %}{% if zone|length > 0 %}{% for device in zone %}{% if loop.last and loop|length > 1 %} and {% elif not loop.first and loop|length > 1 %}, {% endif %}{{ device.name }}{% endfor %}{% if zone|length == 1 %} is{% if name != "not_home" %} at{% endif %}{% else %} are{% endif %} {{ name|replace('_', ' ') }}.{% endif %} {% endfor %}
    data:
      data:
        push:
          sound: US-EN-Alexa-Good-Night.wav
