- platform: mqtt
  state_topic: "smartthings/Front Door Sensor/battery/state"
  name: "Front Door SmartThings Sensor Battery"
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "smartthings/Front Door Sensor/temperature/state"
  name: "Front Door SmartThings Sensor Temperature"
  unit_of_measurement: "°F"

- platform: mqtt
  state_topic: "smartthings/Front Door Sensor/threeAxis/state"
  name: "Front Door SmartThings Sensor Three Axis Gyro"

- platform: mqtt
  state_topic: "owntracks/robbiet480/7plus"
  name: "OwnTracks - Robbie's iPhone 7 Plus Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"
