- platform: mqtt
  state_topic: "smartthings/Front Door Sensor/acceleration/state"
  name: "Front Door SmartThings Acceleration Sensor"
  payload_on: "active"
  payload_off: "inactive"
  sensor_class: "vibration"

- platform: mqtt
  state_topic: "smartthings/Front Door Sensor/contact/state"
  name: "Front Door SmartThings Contact Sensor"
  payload_on: "open"
  payload_off: "closed"
  sensor_class: "opening"
