- platform: template
  sensors:
    robbies_bed:
      value_template: '{{ states("binary_sensor.robbies_bedroom_bed_occupancy_sensor") == "off" }}'
      friendly_name: "Robbie's Bed"
      device_class: occupancy
